---
title: "ETC5513 Project"
author:
- familyname: XXX
  othernames: XXX
  address: Monash University
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
- familyname: Nguyen
  othernames: James Louis
  address: Monash University
  email: jlngu6@student.monash.edu
  correspondingauthor: true
  qualifications:  XXX
- familyname: Lyubic
  othernames: Samuel
  address: Monash University
  email: slyu0007@student.monash.edu
  correspondingauthor: true
  qualifications:  Masters
- familyname: XXX
  othernames: XXX
  address: Monash University
  email: XXX
  correspondingauthor: true
  qualifications:  XXX
department: Econometrics and Business Statistics \newline add names &\newline add names
organization: Monash University
bibliography: references.bib
biblio-style: authoryear-comp
linestretch: 1.5
output:
  bookdown::pdf_document2:
    template: monashreport2.tex
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library(tidyverse)
library(kableExtra)
library(bookdown)
library(lubridate)
library(gridExtra)
```


```{r data-read, include=FALSE}
data = read.csv("data/wdi_data.csv")
data = data[1:36,]

names(data)[5:54] = c(1970:2019)
names(data)[3] = c("Series")

data_value = data %>%
  select('1970':'2019')

data_value = data.frame(lapply(data_value, as.character), stringsAsFactors =FALSE)
data_value = data.frame(lapply(data_value, as.numeric))

data = data.frame(Series = data$Series, data_value)
names(data)[2:51] = c(1970:2019)

data_long = data %>%
  pivot_longer(`1970`:`2019`, names_to = "Year") %>%
  mutate(Year = as.factor(Year))

#use data_long for analysis.
```


\section*{Introduction}

\section*{Motivation}

\section*{}

\section*{}

\section*{Male and Female Mortality Rates and Birth Rate}

This section will be analysing the impact that female and male mortality rates have on the ratio of females to males in the labor force.

```{r create-long-wide-objects-with-required-variables}
mortality_birth_rate_long <- data_long %>%
  filter(Series %in% c("Ratio of female to male labor force participation rate (%) (national estimate)", "Mortality rate, adult, female (per 1,000 female adults)", "Mortality rate, adult, male (per 1,000 male adults)", "Birth rate, crude (per 1,000 people)")) %>%
  arrange(Year) %>%
  slice(65:188)
    
  
mortality_birth_rate_wider <- mortality_long %>%
  pivot_wider(names_from = Series,
              values_from = value) %>%    
  rename(Male_mortality_rate = "Mortality rate, adult, male (per 1,000 male adults)",
         Female_mortality_rate = "Mortality rate, adult, female (per 1,000 female adults)",
         Ratio_of_female_to_male_labor_force = "Ratio of female to male labor force participation rate (%) (national estimate)",
         Birth_rate_crude = "Birth rate, crude (per 1,000 people)") %>%
  slice(17:47)
```

!!!MAYBE GET RID OF!!!
```{r plot-mortality-birth-rates, eval = FALSE}
figure_mortality_birth_rate <- mortality_birth_rate_long %>%
  #filter(!Series == "Ratio of female to male labor force participation rate (%) (national estimate)") %>% #maybe don't include as not a relative number
  ggplot(aes(x = Year,
         y = log1p(value),
         group = Series,
         color = Series)) +
  geom_line() +
  geom_point() +
  theme(legend.position = "right") +
  theme_bw() +
  labs(title = "Figure visualising the male and female mortality 
                rates and birth rate",
       y = "Log of the rate per 1000 people",
       x = "Year") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
figure_mortality_birth_rate
```

```{r figure-female-and-male-mortality-and-birth-rate-and-labor-force-ratio}
figure_female_male_mortality <- mortality_birth_rate_long %>%
  filter(Series %in% c("Mortality rate, adult, female (per 1,000 female adults)", 
                       "Mortality rate, adult, male (per 1,000 male adults)")) %>%
  ggplot(aes(x = Year,
             y = value,
             group = Series,
             color = Series)) +
  geom_line() +
  geom_point() +
  theme(legend.position = "right") +
  theme_bw() +
  labs(title = "Mortality rate",
       y = "Mortality rate per 1000 people",
       x = "Year") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

figure_birth_rate <- mortality_birth_rate_long %>%
  filter(Series == "Birth rate, crude (per 1,000 people)") %>%
  ggplot(aes(x = Year,
             y = value,
             group = Series,
             color = Series)) +
  geom_line() +
  geom_point() +
  theme(legend.position = "right") +
  theme_bw() +
  labs(title = "Birth rate",
       x = "Year") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

figure_labor_force_ratio <- mortality_birth_rate_long %>%
  filter(Series == "Ratio of female to male labor force participation rate (%) (national estimate)") %>%
  ggplot(aes(x = Year,
             y = value,
             group = Series,
             color = Series)) +
  geom_line() +
  geom_point() +
  theme(legend.position = "right") +
  theme_bw() +
  labs(title = "Labor force ratio",
       x = "Year") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
  
```

```{r combining-the-variable-figures, fig.cap = "Each figure visualises the chosen variables"}
figure_combined_birth_ratio_mortality <- grid.arrange(figure_labor_force_ratio, figure_birth_rate, figure_female_male_mortality, ncol = 3)
```


```{r summary-mortality-variables}
summary_mortality_variables <- mortality__birth_rate_wider %>%
  select(-Year, -Ratio_of_female_to_male_labor_force) %>%
  summary() %>%
  kable(caption = "Summary of the male and female mortality rate variables",
        col.names = c("Mortality rate, adult, male (per 1,000 male adults)",
                      "Mortality rate, adult, female (per 1,000 female adults)",
                      "Birth rate, crude (per 1,000 people)"
                      )) %>%
  kable_styling(bootstrap_options = c("hover", "striped"),
                latex_options = "hold_position")
summary_mortality_variables
```

```{r percent-change-over-the-observed-time-period, fig.cap = "Figure showing the percentage chance in each of the chosen variables"}
pct_change_mortality_variables <- mortality_birth_rate_long %>%
  filter(Year %in% c("1986", "2016")) %>% 
  pivot_wider(names_from = Year,
              values_from = value) %>%
  mutate(percent_change_1986_to_2016 = ((`2016`-`1986`)/`1986`)*100) %>%
  kable(caption = "The total percentage change from 1986 to 2016, per each variable") %>%
  kable_styling(bootstrap_options = c("hover", "striped"),
                latex_options = "hold_position") 
pct_change_mortality_variables    
```

```{r percent-change-year-on-end-function}
pct_change_function <- function(v){
  mortality_birth_rate_long %>%
    filter(Series == v) %>%
    ungroup() %>%
    mutate(pct_change = round((((value/lag(value)) - 1)*100), 2))
}
```

```{r percent-change-year-on-end-variables}
pct_change_male_mortality <- pct_change_function("Mortality rate, adult, male (per 1,000 male adults)")
pct_change_female_mortality <- pct_change_function("Mortality rate, adult, female (per 1,000 female adults)")
pct_change_labor_force_ratio <- pct_change_function("Ratio of female to male labor force participation rate (%) (national estimate)")
pct_change_birth_rate <- pct_change_function("Birth rate, crude (per 1,000 people)")

pct_change_combined <- rbind(pct_change_male_mortality, pct_change_female_mortality, pct_change_birth_rate, pct_change_labor_force_ratio) %>%
  replace_na(list(pct_change = 0))
  
```

```{r plot-percent-change-variables}
figure_percent_change_variables <- pct_change_combined %>%
  ggplot(aes(x = Year,
             y = pct_change,
             group = Series,
             color = Series)) +
  geom_line() +
  geom_point() +
  facet_wrap(~Series) +
  theme(legend.position = "right") +
  theme_bw() 

figure_percent_change_variables
```

```{r percent-change-against-labor-force-function}
function_plot_pct_change_against_labor_force_ratio <- function(x){
  pct_change_combined %>%
  filter(Series %in% c("Ratio of female to male labor force participation rate (%) (national estimate)",
                       x)) %>%
    ggplot(aes(x = Year,
             y = pct_change,
             group = Series,
             color = Series)) +
    geom_line() +
    geom_point() +
    geom_smooth(method = lm, se = FALSE) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    theme(legend.position = "bottom")
}
```


```{r figure-pct-change-variables-against-labor-ratio-pct-change}
figure_pct_change_female_mortality_rate_labor_force <- function_plot_pct_change_against_labor_force_ratio("Mortality rate, adult, female (per 1,000 female adults)")
figure_pct_change_male_mortality_rate_labor_force <- function_plot_pct_change_against_labor_force_ratio("Mortality rate, adult, male (per 1,000 male adults)")
figure_pct_change_birth_rate_mortality_rate_labor_force <- function_plot_pct_change_against_labor_force_ratio("Birth rate, crude (per 1,000 people)")
```

```{r plot-the-percent-change-against-each-other}
pct_change_variables_wider <- pct_change_combined %>%
  select(-value) %>%
  group_by(Year) %>%
  pivot_wider(names_from = Series,
              values_from = pct_change) %>%
  rename(Male_mortality_rate = "Mortality rate, adult, male (per 1,000 male adults)",
         Female_mortality_rate = "Mortality rate, adult, female (per 1,000 female adults)",
         Birth_rate = "Birth rate, crude (per 1,000 people)",
         Labor_force_rate = "Ratio of female to male labor force participation rate (%) (national estimate)")
```



\section*{}

\section*{Model}

\section*{Conclusion}